export enum UserLogType {
  AccountCreated = "Account Created",
  AccountUpdated = "Account Updated",
  AccountDeleted = "Account Deleted",
  SecurityBreach = "Security Breach",
  PasswordChanged = "Password Changed",
  UserLoggedIn = "User Logged In",
  UserLoggedOut = "User Logged Out",
  CardCreated = "Card Created",
  CardUpdated = "Card Updated",
  CardDeleted = "Card Deleted",
  CardViewed = "Card Viewed",
  CardShared = "Card Shared",
  CardDownloaded = "Card Downloaded",
  CardPrinted = "Card Printed",
  RefreshToken = "Refresh Token",
  EmailVerified = "Email Verified",
  EmailSent = "Email Sent",
  MainCardSet = "Main Card Set",
}
